default: &default
 adapter: postgresql
 encoding: unicode
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 username: root
 password: root
 host: 127.0.0.1

development:
 <<: *default
 database: wonderful_pots_app_development

test:
 <<: *default
 database: wonderful_pots_app_test

production:
 <<: *default
 database: wonderful_pots_app_production
 password: <%= ENV['WONDERFUL_POST_APP_DATABASE_PASSWORD'] %>
